Fixed Bug #1309706
I'm no Linux developer but I'm pretty sure this is correct.

Bug's exception on my machine:
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: org.freedesktop.DBus.Error.UnknownMethod: Method "Get" with signature "ss" on interface "org.freedesktop.UPower" doesn't exist

  at Docky.Services.SystemService+IUPowerProxy.Get (System.String interface, System.String propname) [0x00000] in <filename unknown>:0
  at Docky.Services.SystemService.HandleUPowerChanged () [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x00137>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x00032>
at System.Delegate.DynamicInvokeImpl (object[]) <0x00203>
at System.MulticastDelegate.DynamicInvokeImpl (object[]) <0x0003b>
at System.Delegate.DynamicInvoke (object[]) <0x00020>
at DBus.Connection.HandleSignal (DBus.Protocol.Message) <0x0031f>
at DBus.Connection.DispatchSignals () <0x00067>
at DBus.Connection.Iterate () <0x0002f>
at DBus.BusG/<Init>c__AnonStorey0.<>m__0 (intptr,DBus.GLib.IOCondition,intptr) <0x0003b>
at (wrapper native-to-managed) DBus.BusG/<Init>c__AnonStorey0.<>m__0 (intptr,DBus.GLib.IOCondition,intptr) <0x0008a>
at (wrapper managed-to-native) Gtk.Application.gtk_main () <0x00054>
at Gtk.Application.Run () <0x0000b>
at Docky.Docky.Main (string[]) <0x005cb>

[ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: org.freedesktop.DBus.Error.UnknownMethod: Method "Get" with signature "ss" on interface "org.freedesktop.UPower" doesn't exist

  at Docky.Services.SystemService+IUPowerProxy.Get (System.String interface, System.String propname) [0x00000] in <filename unknown>:0
  at Docky.Services.SystemService.HandleUPowerChanged () [0x00000] in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x00137>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x00032>
at System.Delegate.DynamicInvokeImpl (object[]) <0x00203>
at System.MulticastDelegate.DynamicInvokeImpl (object[]) <0x0003b>
at System.Delegate.DynamicInvoke (object[]) <0x00020>
at DBus.Connection.HandleSignal (DBus.Protocol.Message) <0x0031f>
at DBus.Connection.DispatchSignals () <0x00067>
at DBus.Connection.Iterate () <0x0002f>
at DBus.BusG/<Init>c__AnonStorey0.<>m__0 (intptr,DBus.GLib.IOCondition,intptr) <0x0003b>
at (wrapper native-to-managed) DBus.BusG/<Init>c__AnonStorey0.<>m__0 (intptr,DBus.GLib.IOCondition,intptr) <0x0008a>
at (wrapper managed-to-native) Gtk.Application.gtk_main () <0x00054>
at Gtk.Application.Run () <0x0000b>
at Docky.Docky.Main (string[]) <0x005cb>

Occurred after Docky ran for some time or after sleep/wake
This should be fixed now

Signed-off-by: Rohan Mathur <rohan@rmathur.com>